### ISSUE TITLE
SAML Security Token terminology

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.BasicAudit#10]
3:5.7.4 SAML Security Token defines a SAML Security Token to be 

"In this section we use the term “SAML Security Token” in a general sense to refer to either (a) a XUA SAML token being used in an [ITI-40](https://profiles.ihe.net/ITI/TF/Volume2/ITI-40.html#3.40), or (b) any other SAML token used to secure an Interoperability transaction."

This includes IUA with the SAML option, which is a OAuth Security Token discussed in 3:5.7.5 OAuth Security Token. 

I suggest to use the term "X-User Assertion" for section 3:5.7.4 and restricting the text XUA.  

Note: According to WS-Trust specification which is referenced in XUA, the X-User Assertion returned to the X-Service User should be opaque and may be encrypted. Also just returning a link where the assertion can be retrieved by the X-Service Provider. Thus there is no principal difference between Oauth and SAML.

**Comment by JohnMoehrke** [comment]
I note in most uses IHE has for XUA (XDS, XCA, XCPD) the client has the full SAML XML. Are you reading my text to be reliant on the SAML Browser SSO Profile? XUA does not call upon the Browser SSO Profile. In fact XUA has no guidance on how to use with http REST. Which might be a stronger argument for removing the SAML section, or moving the SAML section to another chapter completely. My vision of the SAML section was focused on normative IHE uses of XUA, and not constrained to http REST.

I should create a third option where some fragment of the opaque blob is used? 

agree that X-User Assertion might be more proper IHE wording. I was hoping to use terms that would apply to any use of SAML, even those not specifically XUA.
