### ISSUE TITLE
don't escape resource-id when cx type in balp for json

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.BasicAudit#101]
**Is your feature request related to a problem? Please describe.**

1. the example https://profiles.ihe.net/ITI/BALP/AuditEvent-ex-auditPoke-SAML-QDI-Comp.json.html
provides the resource-id in an escaped format:

```json
        {
          "type" : "urn:oasis:names:tc:xacml:2.0:resource:resource-id",
          "valueString" : "500000000^^^&amp;2.16.840.1.113883.3.333&amp;ISO"
        }
```
and in xml twice escaped:

https://profiles.ihe.net/ITI/BALP/AuditEvent-ex-auditPoke-SAML-QDI-Comp.xml.html
```xml
 <detail>
      <type value="urn:oasis:names:tc:xacml:2.0:resource:resource-id"/>
      <valueString
                   value="500000000^^^&amp;amp;2.16.840.1.113883.3.333&amp;amp;ISO"/>
    </detail>
```

**Describe the solution you'd like**
I would have expected 500000000^^^&2.16.840.1.113883.3.333&ISO in json (non escaped) and only once escaped in xml

2. the min sample https://profiles.ihe.net/ITI/BALP/AuditEvent-ex-auditPoke-SAML-QDI-Min.html
has the description of the comprehensive sample

**Comment by JohnMoehrke** [comment]
agree.
