### ISSUE TITLE
IHE.BasicAudit.PatientCreate uses slicing.discriminator.type of `pattern`

### ISSUE THREAD

**Issue by vassilpeytchev** [IHE/ITI.BasicAudit#108]
**Is your feature request related to a problem? Please describe.**
IHE.BasicAudit.PatientCreate uses slicing.discriminator.type of `pattern` which is deprecated and is causing warnings downstream.
Example of an error:
```
The discriminator type 'pattern' is deprecated in R5+. For future compatibility, you could consider using type=value with a pattern[x] instead (if this is not an inherited slicing)
```

**Describe the solution you'd like**
use type of `value`.

**Comment by JohnMoehrke** [comment]
This has already been incorporated into current (ci) build with issue #105 . We do not see this alone as enough of an issue to warrant a release. The #pattern code is not deprecated in FHIR R4.

In your IG that depends on BALP, just ignore the warnings.
