### ISSUE TITLE
ATX: FHIR Feed Option should be explained/linked or referenced

### ISSUE THREAD

**Issue by DavidPyke** [IHE/ITI.BasicAudit#14]
Section: 1:52.1.1 Actor Descriptions and Actor Profile Requirements refers to the ATX: FHIR Feed Option without reference to what that is or where to find it.  That should be added as a link to the PDF.

**Comment by JohnMoehrke** [comment]
I don't disagree, but by linking to the PDF this puts a need to update this when the PDF is either converted or integrated. I was trying to avoid a link in this case.

**Comment by JohnMoehrke** [comment]
committee review: point them at the supplement PDF - https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_RESTful-ATNA.pdf

**Comment by JohnMoehrke** [comment]
create an open issue to track this future fix needed
