### ISSUE TITLE
3:5.7.3 RESTful activities describes data operations, not REST

### ISSUE THREAD

**Issue by DavidPyke** [IHE/ITI.BasicAudit#18]
This section describes CRUDE as RESTful activities as opposed to data operations.  Most would assume that http commands such as POST, GET, etc. would be the closest to RESTful activities.  I would suggest that this section be edited to clarify that these operations can be triggered by RESTful transactions but are not RESTful in and of themselves.

**Comment by JohnMoehrke** [comment]
My understanding is that RESTful is the concept of CRUD against resources. RESTful can be implemented with many protocols. HTTP just happens to be the most common. Thus HTTP verbs of POST, GET, etc.. are secondary to the concept of RESTful, not primary.

Hence why FHIR defines the "Instance Level Interactions" of read, vread, update, patch, delete, create.

See Roy Fielding dissertation on REST that started all of this
https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm
----

secondary, I am using "RESTful activities" to tie together the word "activity", which is foundational to auditable events are described as activities.

----

Given these clarifications, i do expect there is some clarifications I could make... so welcome a discussion or recommendation for change.

**Comment by JohnMoehrke** [comment]
@DavidPyke can you provide a recommendation for edits, given the comment and response.

**Comment by JohnMoehrke** [comment]
no details on how to change provided. If some come up during TI they can be accepted.
