### ISSUE TITLE
Name alternatives

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.BasicAudit#19]
Not that this name is bad, but IHE tends to want 3 or 4 letter acronyms
* Basic Audit Accounting for Mobile - BAAm
* Basic Audit Log Pattern - BALP
* Basic Auditing - BA

note that BasicAudit had to be lowercased in the canonical URI due to a bug in the IG publisher (go-publish).

**Comment by JohnMoehrke** [comment]
friday decide.

**Comment by lynnfel** [comment]
An acronym is needed.  Gazelle Master Model (where profile/actor/transaction/option structure is modelled) requires an acronym

**Comment by JohnMoehrke** [comment]
agreed: Basic Audit Log Patterns (BALP)
