### ISSUE TITLE
3:5.7.5 OAuth Security Token should give more attention to SMART and possibly UDAP

### ISSUE THREAD

**Issue by DavidPyke** [IHE/ITI.BasicAudit#23]
3:5.7.5 OAuth Security Token focuses exclusively on IUA which makes some sense as it's the IHE standard. However, as SMART on FHIR is the predominant exchange method of FHIR, some guidance should be given for BasicAudit when SoF used for an IHE FHIR environment. 

In addition, UDAP is also becoming more used (in Carequality and potentially elsewhere) and guidance would likely make BasicAudit more relevant for the future.

**Comment by JohnMoehrke** [comment]
UDAP is not yet published, nothing to work with.

SMART would be great, we just need someone with knowledge and experience to guide us.

Thus, need more persuasive and constructive details.
