### ISSUE TITLE
AuditEvent use documentation in products should be removed 

### ISSUE THREAD

**Issue by DavidPyke** [IHE/ITI.BasicAudit#26]
Listing two implementations (omitting HAPI FHIR) one of which is only listed as "Grahame’s Server" is not a valuable section.  If this is going to be useful, it would need information on at least the top 5 implementations.  Better would remove this section as it's not giving significant guidance for the IHE use case.

**Comment by JohnMoehrke** [comment]
do the others have sections on how to use AuditEvent? That is what these are about.

**Comment by JohnMoehrke** [comment]
I am not sure keeping these links is really important, but it took me great effort to find where each of these do document how to use AuditEvent, thus I felt it might be useful to the BasicAudit reader.

**Comment by JohnMoehrke** [comment]
remove
