### ISSUE TITLE
Actor alignment with ATNA

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.BasicAudit#4]
In Section 1:52.1 BasicAudit Actors and Content Note that the actors in this profile are the same as the actors defined in the [ATNA Profile [ITI TF-1: 9]](https://profiles.ihe.net/ITI/TF/Volume1/ch-9.html) and [Add RESTful ATNA (Query and Feed) Supplement](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_RESTful-ATNA.pdf).

A quick cross-check with ATNA and RESTful ATNA actors show that the actor names are not the same.

**Comment by JohnMoehrke** [comment]
good catch. thanks

**Comment by JohnMoehrke** [comment]
is the concern with "ANY Secure Client" and "ANY Secure Server" actors? I do explain these in section 1:52.1.1.1 and 1:52.1.1.2.  Is this definition not enough?

I think the other actors are the right actors from ATNA.

or is the concern something else.
