### ISSUE TITLE
double recording

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.BasicAudit#5]
In 1:52.1.1.1 ANY Secure Client

"The double recording will be different as the the AuditEvent.source would identify the actor recording the event."

I guess it should read "The double recorded messages in general will be different as the the AuditEvent.source would identify the actor recording the event."

**Comment by JohnMoehrke** [comment]
is your point that they might be different for other reasons. This reason given is just the minimal difference. The main reason for me to point this out is to indicate how one can differentiate between an audit event recorded on the client vs an audit event recorded on the server; even if all other data recorded was identical.

**Comment by msmock** [comment]
No. It's just a grammar thing. 'The double recording' is singular and covers both messages, where the messages differ.
