### ISSUE TITLE
1:52.1.1.3 ATNA Audit Record Repository

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.BasicAudit#6]
Says "The Audit Record Repository shown is not specialized, it is the ATNA Audit Record Repository with support for ATNA ATX:FHIR Feed Option, and Retrieve Audit Message Option."

Isn't the Audit Record Repository specialized with the second part of the sentence?

**Comment by JohnMoehrke** [comment]
those are named options. they are not new options. The intended point of 'not specialized' is to say that this IG is just using existing actors, profiles, and options from ATNA.

seems the wording could be more clear.
