### ISSUE TITLE
Basic RESTful AuditEvent Profiles imply that OAuth is mandatory

### ISSUE THREAD

**Issue by jamesagnew** [IHE/ITI.BasicAudit#61]
**Section Number** 

[3:5.7.3](https://profiles.ihe.net/ITI/BALP/StructureDefinition-IHE.BasicAudit.Query.html)

**Issue**

The basic AuditEvent RESTful profiles include a bullet with the text `And OAuth is used to authorize both app and user` in the scenario descriptions. I have two comments on this:

* This text seems to imply that this profile is only applicable specifically for OAuth-authenticated transactions. While it is likely that in production FHIR systems, OAuth2/OIDC will be the dominant auth mechanism, it seems overly restrictive to limit these profiles to that.
* More of a nitpick, but I would personally replace `OAuth` with `OAuth2/OIDC` since it is very unlikely to encounter any FHIR systems using the legacy OAuth spec.

**Proposed Change**

Suggested text might be:

> This profile includes an optional user slice that can be populated appropriately for transactions authenticated using OAuth2/OIDC.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
I am not clear on the distinction between OAuth and OAuth2/OIDC... In my view OAuth is broader and includes when OAuth2 and/or OIDC are used. To be specific to OAuth2 and/or OIDC would be too restricted without good reason.

**Comment by JohnMoehrke** [comment]
fixes are only to narrative, so no normative impact.
