### ISSUE TITLE
Query Parameter Handling

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.BasicAudit#7]
Section 1:52.4.1.4 Query Parameter Handling speaks of search use cases only, but does not speak of queries in other context (e.g., Authorization Requests)

**Comment by JohnMoehrke** [comment]
I have explicitly put the workflow around getting and validating security tokens out of scope for this IG, as they are covered in IUA and XUA.

**Comment by msmock** [comment]
My point is not on the security aspects. My point is that with RESTful there are http query parameter which are not used for searches, but to transfer data. It's not clear to me, whether the section is on http query parameter in general or restricted to searches.

**Comment by JohnMoehrke** [comment]
committee discussion:
1. Need examples to better understand
2. Current text is only addressing classic REST interactions, not all possible uses of http
3. We might identify additional things that should eventual be included, but put them as Open Issues out of scope at this time.

**Comment by msmock** [comment]
Redundant, if the section "1:52.4.1.4 Query Parameter Handling" is on RESTful query parameter only.
