### ISSUE TITLE
Described use of Source and Destination Role ID does not agree with profile use.

### ISSUE THREAD

**Issue by ElliotSilver** [IHE/ITI.BasicAudit#75]
**Section Number** 3:5.7.3 Restful activities

**Issue** Ascribed source and destination roles do not match profiles. Profiles do not consistently use client as Source and server as Destination. This is likely an error in the narrative rather than in the profiles.

**Proposed Change** Rephrase first sentence of section to align with actual use of Source and Destination Roles.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
The narrative in 3:5.7.3 does seem to be sometimes wrong. Mostly the paragraph forgot that Create and Update are also different. Given the rest of the paragraph, I think this was more my speaking to the Public-Comment, and should have been marked to be cleaned up before release.

I checked that the profiles are correct, so the following aligns the paragraph to the profiles:

> Create, Update, and Query follow a similar pattern where the initiator (client) of the RESTful interaction is identified as the Source Role ID and the responder (server) is the Destination Role ID. Read pattern with the (client) of the RESTful interaction, which will receive the data, is considered the Destination Role ID and the responder (server) is the Source Role ID.  This pattern is found in both DICOM and XDS.  Delete uses of a pattern with (client) of the RESTful interaction is indicated as the Application and (server) of the RESTful interaction is indicated as the Custodian.

**Comment by lukeaduncan** [comment]
@ElliotSilver do you agree with the paragraph modifications in the previous comment?
