### ISSUE TITLE
Pattern slicing of CodableConcepts incorrectly includes display values

### ISSUE THREAD

**Issue by ElliotSilver** [IHE/ITI.BasicAudit#78]
**Section Number** 

Profiles throughout

**Issue** 

In several profiles, pattern-type slicing discriminators of CodeableConcept (and possibly, Coding and code) elements incorrectly includes the display values in the slice definitions. This means that (a) a code display value is necessary to meet the slice definition, and (b) the specific display value used is necessary to meet the slice definition. This reduces profile usability for environments which may prefer to omit display values for resource size, do not need the clarity that a display value can provide, or which operate in other languages.

**Proposed Change**

Omit display values for codes used as slicing discriminators (and probably elsewhere in the profile definitions).

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
@ElliotSilver , so are you saying that 
```
* agent[source].type = DCM#110153 "Source Role ID"
* agent[source].who 1..1
* agent[source].network 1..1
* agent[recipient] obeys val-audit-source
* agent[recipient].type = DCM#110152 "Destination Role ID"
* agent[recipient].who 1..1
* agent[recipient].network 1..1
```
should be
```
* agent[source].type = DCM#110153
* agent[source].who 1..1
* agent[source].network 1..1
* agent[recipient] obeys val-audit-source
* agent[recipient].type = DCM#110152
* agent[recipient].who 1..1
* agent[recipient].network 1..1
```

**Comment by ElliotSilver** [comment]
Correct. See https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Best.20practice.20for.20constraining.20CodeableConcepts.20and.20Coding.

Although, I'd leave the display values as comments.
