### ISSUE TITLE
Fixed values need explicit minimum cardinality of 1

### ISSUE THREAD

**Issue by ElliotSilver** [IHE/ITI.BasicAudit#92]
**Section Number** All profiles

**Issue** Fixed values (and similar) need minimum cardinality specified. 

From IHE.BasicAudit.Read:
```
* agent[user].requestor = true
...
* entity[data].type = http://terminology.hl7.org/CodeSystem/audit-entity-type#2 // "System Object"
* entity[data].role from RestObjectRoles (required)
* entity[data].what 1..1
* entity[data].securityLabel ^short = "may contain the security labels on the resource returned"
```
Neither `requestor`, nor `role` are actually required, although if present, `requestor` must be `true` and `role` must be from the specified ValueSet.

If we wish fixed values (and similar) to actually be required, we need to add minimum cardinality.

(Note, `type` doesn't need a min cardinality specified as it is automatically required as part of the discriminator.)

**Proposed Change** Review *all* profiles and add minimum cardinality of 1 on elements expected to be present. If the element is a child element, make sure the parent element also has minimum cardinality specified.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
agree bug, missed pattern. Not clear this is a issue/PR or needs to be CP.

**Comment by JohnMoehrke** [comment]
I don't think that .type is a problem as it is what is slicing discriminator.

**Comment by JohnMoehrke** [comment]
Create pull-request to show the scope, and check completeness.
