### ISSUE TITLE
Fix read subtype slicing

### ISSUE THREAD

**Issue by ElliotSilver** [IHE/ITI.BasicAudit#93]
**Section Number** IHE.BasicAudit.Read profile

**Issue** Use of slicing for subtype is unusual and potentially incorrect.

```
* subtype ^slicing.discriminator.type = #value
* subtype ^slicing.discriminator.path = "$this"
* subtype ^slicing.rules = #open // allow other codes
* subtype 1..
* subtype contains anyRead 0..1 and anyVread 0..1
* subtype[anyRead] = http://hl7.org/fhir/restful-interaction#read // "read"
* subtype[anyVread] = http://hl7.org/fhir/restful-interaction#vread // "vread"
```
It isn't clear what the benefit of using two (empty) slices are here. I would have expected a single slice (min cardinality 1) with values from a valueset including only read and, vread. Two optional slices without an invariant to require at least one of them, with open slicing, allows for an instance with any subtype value to meet this profile.

**Proposed Change** Create a "read subtypes" valueset and change profiling to:
```
* subtype ^slicing.discriminator.type = #value
* subtype ^slicing.discriminator.path = "$this"
* subtype ^slicing.rules = #open // allow other codes
* subtype 1..
* subtype contains read 1..1
* subtype[read] from ReadSubtypes (required)
```

Or, actually, since there is no further profiling that depends on the subtype, you could simplify to:
```
* subtype 1..
* subtype from ReadSubtypes (required)
```
(i.e., remove slicing)

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by ElliotSilver** [comment]
Similar issue on search.

**Comment by JohnMoehrke** [comment]
clear bug that this could be extended with a further slice that would enable someone to not include read or vread. So should change.
Not clear if this is issue/PR or would need to be converted to a CP?

**Comment by JohnMoehrke** [comment]
Create pull-request to show the scope, and check completeness.
